"""
Country code lookup tables.

GDELT uses two country code systems that are NOT interchangeable:
  - CAMEO 3-letter codes  → used in Actor1CountryCode / Actor2CountryCode
  - FIPS 10-4 2-letter codes → used in ActionGeo_CountryCode (geographic location)

Both differ from ISO 3166-1 alpha-2 and alpha-3 in important ways.
These dicts are module-level constants (no I/O at runtime).
"""

from __future__ import annotations

# ── CAMEO 3-letter country codes ──────────────────────────────────────────
# Maps common name / ISO alpha-3 → CAMEO code
# CAMEO codes are used for Actor1CountryCode / Actor2CountryCode
CAMEO_COUNTRY_CODES: dict[str, str] = {
    "afghanistan": "AFG",
    "albania": "ALB",
    "algeria": "ALG",
    "angola": "ANG",
    "argentina": "ARG",
    "armenia": "ARM",
    "australia": "AUS",
    "austria": "AUT",
    "azerbaijan": "AZE",
    "bahrain": "BAH",
    "bangladesh": "BNG",
    "belarus": "BLR",
    "belgium": "BEL",
    "bolivia": "BOL",
    "bosnia": "BOS",
    "brazil": "BRA",
    "bulgaria": "BUL",
    "burkina faso": "BFO",
    "cambodia": "CAM",
    "cameroon": "CMR",
    "canada": "CAN",
    "chad": "CHA",
    "chile": "CHL",
    "china": "CHN",
    "colombia": "COL",
    "congo": "CON",
    "democratic republic of congo": "DRC",
    "croatia": "CRO",
    "cuba": "CUB",
    "cyprus": "CYP",
    "czech republic": "CZR",
    "czechia": "CZR",
    "denmark": "DEN",
    "ecuador": "ECU",
    "egypt": "EGY",
    "ethiopia": "ETH",
    "finland": "FIN",
    "france": "FRA",
    "georgia": "GRG",
    "germany": "DEU",
    "ghana": "GHA",
    "greece": "GRC",
    "guatemala": "GUA",
    "guinea": "GUI",
    "haiti": "HAI",
    "hungary": "HUN",
    "india": "IND",
    "indonesia": "INS",
    "iran": "IRN",
    "iraq": "IRQ",
    "ireland": "IRE",
    "israel": "ISR",
    "italy": "ITA",
    "ivory coast": "CDI",
    "jamaica": "JAM",
    "japan": "JPN",
    "jordan": "JOR",
    "kazakhstan": "KAZ",
    "kenya": "KEN",
    "north korea": "PRK",
    "south korea": "KOR",
    "kosovo": "KSV",
    "kuwait": "KUW",
    "kyrgyzstan": "KGZ",
    "laos": "LAO",
    "latvia": "LAT",
    "lebanon": "LEB",
    "libya": "LIB",
    "lithuania": "LIT",
    "luxembourg": "LUX",
    "malaysia": "MAL",
    "mali": "MLI",
    "mexico": "MEX",
    "moldova": "MLD",
    "morocco": "MOR",
    "mozambique": "MZM",
    "myanmar": "MYA",
    "nepal": "NEP",
    "netherlands": "NLD",
    "new zealand": "NZL",
    "niger": "NIG",
    "nigeria": "NGA",
    "norway": "NOR",
    "oman": "OMA",
    "pakistan": "PAK",
    "palestine": "PSE",
    "panama": "PAN",
    "paraguay": "PAR",
    "peru": "PER",
    "philippines": "PHI",
    "poland": "POL",
    "portugal": "POR",
    "qatar": "QAT",
    "romania": "ROM",
    "russia": "RUS",
    "rwanda": "RWA",
    "saudi arabia": "SAU",
    "senegal": "SEN",
    "serbia": "SRB",
    "sierra leone": "SIE",
    "singapore": "SNG",
    "somalia": "SOM",
    "south africa": "SAF",
    "spain": "SPA",
    "sri lanka": "SRI",
    "sudan": "SDN",
    "sweden": "SWE",
    "switzerland": "SWI",
    "syria": "SYR",
    "taiwan": "TAW",
    "tajikistan": "TAJ",
    "tanzania": "TAZ",
    "thailand": "THI",
    "tunisia": "TUN",
    "turkey": "TUR",
    "turkmenistan": "TKM",
    "ukraine": "UKR",
    "united arab emirates": "UAE",
    "uae": "UAE",
    "united kingdom": "GBR",
    "uk": "GBR",
    "britain": "GBR",
    "great britain": "GBR",
    "united states": "USA",
    "usa": "USA",
    "america": "USA",
    "uruguay": "URU",
    "uzbekistan": "UZB",
    "venezuela": "VEN",
    "vietnam": "VIE",
    "west bank": "WSB",
    "gaza": "GZS",
    "gaza strip": "GZS",
    "yemen": "YEM",
    "zambia": "ZAM",
    "zimbabwe": "ZIM",
}

# ── FIPS 10-4 2-letter country codes ─────────────────────────────────────
# Maps common name → FIPS code
# FIPS codes are used for ActionGeo_CountryCode (geographic location of event)
FIPS_COUNTRY_CODES: dict[str, str] = {
    "afghanistan": "AF",
    "albania": "AL",
    "algeria": "AG",
    "angola": "AO",
    "argentina": "AR",
    "armenia": "AM",
    "australia": "AS",
    "austria": "AU",
    "azerbaijan": "AJ",
    "bahrain": "BA",
    "bangladesh": "BG",
    "belarus": "BO",
    "belgium": "BE",
    "bolivia": "BL",
    "bosnia": "BK",
    "brazil": "BR",
    "bulgaria": "BU",
    "burkina faso": "UV",
    "cambodia": "CB",
    "cameroon": "CM",
    "canada": "CA",
    "chad": "CD",
    "chile": "CI",
    "china": "CH",
    "colombia": "CO",
    "congo": "CF",
    "democratic republic of congo": "CG",
    "croatia": "HR",
    "cuba": "CU",
    "cyprus": "CY",
    "czech republic": "EZ",
    "czechia": "EZ",
    "denmark": "DA",
    "ecuador": "EC",
    "egypt": "EG",
    "ethiopia": "ET",
    "finland": "FI",
    "france": "FR",
    "georgia": "GG",
    "germany": "GM",
    "ghana": "GH",
    "greece": "GR",
    "guatemala": "GT",
    "guinea": "GV",
    "haiti": "HA",
    "hungary": "HU",
    "india": "IN",
    "indonesia": "ID",
    "iran": "IR",
    "iraq": "IZ",
    "ireland": "EI",
    "israel": "IS",
    "italy": "IT",
    "ivory coast": "IV",
    "jamaica": "JM",
    "japan": "JA",
    "jordan": "JO",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "north korea": "KN",
    "south korea": "KS",
    "kosovo": "KV",
    "kuwait": "KU",
    "kyrgyzstan": "KG",
    "laos": "LA",
    "latvia": "LG",
    "lebanon": "LE",
    "libya": "LY",
    "lithuania": "LH",
    "luxembourg": "LU",
    "malaysia": "MY",
    "mali": "ML",
    "mexico": "MX",
    "moldova": "MD",
    "morocco": "MO",
    "mozambique": "MZ",
    "myanmar": "BM",
    "nepal": "NP",
    "netherlands": "NL",
    "new zealand": "NZ",
    "niger": "NG",
    "nigeria": "NI",
    "norway": "NO",
    "oman": "MU",
    "pakistan": "PK",
    "palestine": "WE",
    "panama": "PM",
    "paraguay": "PA",
    "peru": "PE",
    "philippines": "RP",
    "poland": "PL",
    "portugal": "PO",
    "qatar": "QA",
    "romania": "RO",
    "russia": "RS",
    "rwanda": "RW",
    "saudi arabia": "SA",
    "senegal": "SG",
    "serbia": "RI",
    "sierra leone": "SL",
    "singapore": "SN",
    "somalia": "SO",
    "south africa": "SF",
    "spain": "SP",
    "sri lanka": "CE",
    "sudan": "SU",
    "sweden": "SW",
    "switzerland": "SZ",
    "syria": "SY",
    "taiwan": "TW",
    "tajikistan": "TI",
    "tanzania": "TZ",
    "thailand": "TH",
    "tunisia": "TS",
    "turkey": "TU",
    "turkmenistan": "TX",
    "ukraine": "UP",
    "united arab emirates": "AE",
    "uae": "AE",
    "united kingdom": "UK",
    "uk": "UK",
    "britain": "UK",
    "great britain": "UK",
    "united states": "US",
    "usa": "US",
    "america": "US",
    "uruguay": "UY",
    "uzbekistan": "UZ",
    "venezuela": "VE",
    "vietnam": "VM",
    "west bank": "WE",
    "gaza": "GZ",
    "gaza strip": "GZ",
    "yemen": "YM",
    "zambia": "ZA",
    "zimbabwe": "ZI",
}

# ── CAMEO Event Root Codes ────────────────────────────────────────────────
# Maps root code → human-readable label
CAMEO_ROOT_CODE_LABELS: dict[str, str] = {
    "01": "MAKE PUBLIC STATEMENT",
    "02": "APPEAL",
    "03": "EXPRESS INTENT TO COOPERATE",
    "04": "CONSULT",
    "05": "ENGAGE IN DIPLOMATIC COOPERATION",
    "06": "ENGAGE IN MATERIAL COOPERATION",
    "07": "PROVIDE AID",
    "08": "YIELD",
    "09": "INVESTIGATE",
    "10": "DEMAND",
    "11": "DISAPPROVE",
    "12": "REJECT",
    "13": "THREATEN",
    "14": "PROTEST",
    "15": "EXHIBIT FORCE POSTURE",
    "16": "REDUCE RELATIONS",
    "17": "COERCE",
    "18": "ASSAULT",
    "19": "FIGHT",
    "20": "USE UNCONVENTIONAL MASS VIOLENCE",
}


def lookup_cameo_code(country_name: str) -> str | None:
    """Return the CAMEO country code for a given country name (case-insensitive)."""
    return CAMEO_COUNTRY_CODES.get(country_name.lower().strip())


def lookup_fips_code(country_name: str) -> str | None:
    """Return the FIPS 10-4 country code for a given country name (case-insensitive)."""
    return FIPS_COUNTRY_CODES.get(country_name.lower().strip())


def get_root_code_label(root_code: str) -> str:
    """Return the human-readable label for a CAMEO root code."""
    return CAMEO_ROOT_CODE_LABELS.get(root_code, root_code)
